ci:
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: "^tests/roots"
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 7c55798a78262d14b2074abf623d8a992ebb70d4  # frozen: v0.16.2
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        exclude: "$sphinxcontrib/moderncmakedomain/(cmake|colors).py$"
      - id: ruff-format
        exclude: "$sphinxcontrib/moderncmakedomain/(cmake|colors).py$"

  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: ca7cdf44b934945a5ea5e02c09a4a68b42125ebd  # frozen: 2026.08.08
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 12e63946db2c5cfcc9030fac21c3883ba88c6ed8  # frozen: 0.38.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa  # frozen: v1.29.0
    hooks:
      - id: zizmor
        files: "^\\.github"
        args: [--persona=pedantic]
