ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.18.0
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.47"
  hooks:
  - id: check-manifest
    stages: [manual]
