name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

permissions: {}

jobs:
  check-package:
    name: Build & inspect
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1

  test:
    name: Run quick tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - uses: wntrblm/nox@3284968a16fa5bd7fc0cc64a69a531404ccb4756 # 2026.07.11
        with:
          python-versions: "3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14"

      - name: Test Python 3.8
        run: nox -s tests -P 3.8

      - name: Test Python 3.9
        run: nox -s tests -P 3.9

      - name: Test Python 3.10
        run: nox -s tests -P 3.10

      - name: Test Python 3.11
        run: nox -s tests -P 3.11

      - name: Test Python 3.12
        run: nox -s tests -P 3.12

      - name: Test Python 3.13
        run: nox -s tests -P 3.13

      - name: Test Python 3.14
        run: nox -s tests -P 3.14
